{
    'name': 'Return Merchandise Authorization Management',
    'summary': 'Return Merchandise Authorization (RMA)',
    'version': '17.0.1.0',
    'category': 'Sales',
    'website': 'https://electron.sa',
    'author': 'Electron Technology',
    'depends': ['account_accountant', 'sale_management', 'stock_account', 'stock', 'mail', 'web'],
    "data": [
        "views/report_rma.xml",
        "report/report.xml",
        "data/mail_data.xml",
        "data/rma_operation_data.xml",
        "data/stock_data.xml",
        "security/rma_security.xml",
        "security/ir.model.access.csv",
        "wizard/stock_picking_return_views.xml",
        "wizard/rma_delivery_views.xml",
        "wizard/rma_finalization_wizard_views.xml",
        "wizard/rma_split_views.xml",
        "views/menus.xml",
        "views/res_partner_views.xml",
        "views/rma_finalization_views.xml",
        "views/rma_portal_templates.xml",
        "views/rma_team_views.xml",
        "views/rma_views.xml",
        "views/rma_tag_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_warehouse_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
}